on: [push]

name: nightly

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
